<?php

declare(strict_types=1);

namespace Camada\Tests;

use Camada\Snapshot\FileWords;
use Camada\Snapshot\Matcher;
use Camada\Snapshot\MatchInput;
use Camada\Snapshot\MatchResult;
use Camada\Snapshot\MemoryWords;
use Camada\Snapshot\Parser;
use Camada\Snapshot\WordSource;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Golden conformance: fixtures generated by edge-analyst/scripts/gen-fixtures.mjs, with expected
 * outputs computed by running the reference implementation (src/blocklist.js) itself. A failure
 * here means the port drifted from the format owner — fix the port, never the fixture. This is
 * the PHP twin of camada-core/test/conformance.test.ts, case for case — run over BOTH word
 * sources, which is what proves the seeking (file-backed) matcher equals the in-memory one.
 */
final class ConformanceTest extends TestCase
{
    /** @return iterable<string, array{string}> */
    public static function sources(): iterable
    {
        yield 'memory' => ['memory'];
        yield 'file' => ['file'];
    }

    /** @return iterable<string, array{string, string}> */
    public static function versionsAndSources(): iterable
    {
        foreach (['v3', 'v4'] as $v) {
            foreach (self::sources() as $name => [$s]) {
                yield "{$v}-{$name}" => [$v, $s];
            }
        }
    }

    public static function words(string $source, string $rel): WordSource
    {
        return $source === 'file' ? FileWords::open(Fixtures::path($rel)) : new MemoryWords(Fixtures::bin($rel));
    }

    public static function matcher(string $source, string $name, string $d = 'blk3'): Matcher
    {
        return new Matcher(Parser::parse(self::words($source, "{$d}/{$name}.bin"), Fixtures::json("{$d}/{$name}.meta.json")));
    }

    /** @return list<array<string, mixed>> */
    private static function cases(string $version, string $kind): array
    {
        $all = Fixtures::json('blk3/cases.json');
        /** @var array<string, array<string, list<array<string, mixed>>>> $all */
        return $all[$version][$kind];
    }

    /** @return list<array<string, mixed>> */
    private static function cases5(string $kind): array
    {
        $all = Fixtures::json('blk5/cases.json');
        /** @var array<string, array<string, list<array<string, mixed>>>> $all */
        return $all['v5'][$kind];
    }

    /**
     * A v5 case's `headers` is a map with already lower-cased keys — the request as the tap sees
     * it. It becomes the header(name) getter §D3 defines, exactly as the reference harness does.
     *
     * @param array<string, mixed> $c
     */
    public static function asInput(array $c, bool $blind = false): MatchInput
    {
        /** @var array<string, mixed> $i */
        $i = $c['input'];
        /** @var array<string, string>|null $headers */
        $headers = $i['headers'] ?? null;
        /** @var int|null $asn */
        $asn = $i['asn'] ?? null;
        return new MatchInput(
            ip: isset($i['ip']) ? (string) $i['ip'] : null,
            asn: $asn,
            country: isset($i['country']) ? (string) $i['country'] : null,
            tlsx: isset($i['tlsx']) ? (string) $i['tlsx'] : null,
            path: isset($i['path']) ? (string) $i['path'] : null,
            ua: isset($i['ua']) ? (string) $i['ua'] : null,
            header: $headers !== null && !$blind ? static fn (string $n): ?string => $headers[$n] ?? null : null,
        );
    }

    /** @return array<string, mixed> */
    private static function outcome(MatchResult $r): array
    {
        // the reference reports "nothing matched" as reason null; the port leaves it null too
        return ['block' => $r->block, 'challenge' => $r->challenge, 'allowed' => $r->allowed, 'reason' => $r->reason];
    }

    /** @return array<string, mixed> */
    private static function outcome5(MatchResult $r): array
    {
        return self::outcome($r) + ['warn' => $r->warn, 'action' => $r->action, 'rule' => $r->rule];
    }

    /** @param array<string, mixed> $c */
    private static function label(array $c): string
    {
        return (string) json_encode($c['input']);
    }

    /**
     * @param array<string, mixed> $expect
     * @param array<string, mixed> $got
     */
    private static function assertOutcome(array $expect, array $got, string $label): void
    {
        ksort($expect);
        ksort($got);
        self::assertSame($expect, $got, $label);
    }

    #[DataProvider('versionsAndSources')]
    public function testBasic(string $version, string $source): void
    {
        $m = self::matcher($source, "{$version}-basic");
        foreach (self::cases($version, 'basic') as $c) {
            /** @var array<string, mixed> $expect */
            $expect = $c['expect'];
            self::assertOutcome($expect, self::outcome($m->match(self::asInput($c))), self::label($c));
        }
    }

    #[DataProvider('versionsAndSources')]
    public function testEmpty(string $version, string $source): void
    {
        $m = self::matcher($source, "{$version}-empty");
        foreach (self::cases($version, 'empty') as $c) {
            /** @var array<string, mixed> $expect */
            $expect = $c['expect'];
            self::assertOutcome($expect, self::outcome($m->match(self::asInput($c))), self::label($c));
        }
    }

    #[DataProvider('sources')]
    public function testV4NeverTwoOutcomeFlags(string $source): void
    {
        $m = self::matcher($source, 'v4-basic');
        foreach (array_merge(self::cases('v4', 'basic'), self::cases('v4', 'empty')) as $c) {
            $r = $m->match(self::asInput($c));
            self::assertLessThanOrEqual(1, (int) $r->allowed + (int) $r->block + (int) $r->challenge);
        }
    }

    #[DataProvider('sources')]
    public function testV3ContainerCannotExpressAllowOrChallenge(string $source): void
    {
        $v3 = self::matcher($source, 'v3-basic');
        $v4Cases = self::cases('v4', 'basic');
        $v3Cases = self::cases('v3', 'basic');
        self::assertCount(count($v3Cases), $v4Cases);
        $diverged = 0;
        foreach ($v4Cases as $k => $v4c) {
            if ($v4c['expect'] === $v3Cases[$k]['expect']) {
                continue;
            }
            $diverged++;
            /** @var array<string, mixed> $expect */
            $expect = $v3Cases[$k]['expect'];
            self::assertOutcome($expect, self::outcome($v3->match(self::asInput($v4c))), self::label($v4c));
        }
        self::assertGreaterThan(0, $diverged);   // the fixtures must actually exercise the new sections
    }

    #[DataProvider('sources')]
    public function testV5Rules(string $source): void
    {
        $m = self::matcher($source, 'v5-rules', 'blk5');
        foreach (self::cases5('rules') as $c) {
            /** @var array<string, mixed> $expect */
            $expect = $c['expect'];
            self::assertOutcome($expect, self::outcome5($m->match(self::asInput($c))), self::label($c));
        }
    }

    #[DataProvider('sources')]
    public function testV5Empty(string $source): void
    {
        $m = self::matcher($source, 'v5-empty', 'blk5');
        foreach (self::cases5('empty') as $c) {
            /** @var array<string, mixed> $expect */
            $expect = $c['expect'];
            self::assertOutcome($expect, self::outcome5($m->match(self::asInput($c))), self::label($c));
        }
    }

    #[DataProvider('sources')]
    public function testV5NeverTwoOutcomeFlags(string $source): void
    {
        $m = self::matcher($source, 'v5-rules', 'blk5');
        foreach (array_merge(self::cases5('rules'), self::cases5('empty')) as $c) {
            $r = $m->match(self::asInput($c));
            self::assertLessThanOrEqual(1, (int) $r->allowed + (int) $r->block + (int) $r->challenge + (int) $r->warn);
        }
    }

    #[DataProvider('sources')]
    public function testV5NamesTheRuleOnlyWhenARuleDecided(string $source): void
    {
        $m = self::matcher($source, 'v5-rules', 'blk5');
        foreach (self::cases5('rules') as $c) {
            $r = $m->match(self::asInput($c));
            if ($r->reason === 'rule') {
                self::assertNotNull($r->rule);
                self::assertNotNull($r->action);
            } else {
                self::assertNull($r->rule);
                self::assertNull($r->action);
            }
        }
    }

    #[DataProvider('sources')]
    public function testV5RulesOverruleTheSidesAV4ContainerCanOnlyRead(string $source): void
    {
        $v4 = self::matcher($source, 'v4-basic');
        $rules = self::matcher($source, 'v5-rules', 'blk5');
        $diverged = 0;
        foreach (self::cases5('rules') as $c) {
            if (self::outcome($v4->match(self::asInput($c))) === self::outcome($rules->match(self::asInput($c)))) {
                continue;
            }
            $diverged++;
            /** @var array<string, mixed> $expect */
            $expect = $c['expect'];
            self::assertSame('rule', $expect['reason']);
        }
        self::assertGreaterThan(0, $diverged);
    }

    #[DataProvider('sources')]
    public function testV5HeaderCasesDecideThroughTheGetterAlone(string $source): void
    {
        $m = self::matcher($source, 'v5-rules', 'blk5');
        $seen = 0;
        foreach (self::cases5('rules') as $c) {
            /** @var array<string, mixed> $input */
            $input = $c['input'];
            if (!isset($input['headers']) || $input['headers'] === []) {
                continue;
            }
            $seen++;
            /** @var array<string, mixed> $expect */
            $expect = $c['expect'];
            self::assertOutcome($expect, self::outcome5($m->match(self::asInput($c))), self::label($c));
            $blind = $m->match(self::asInput($c, blind: true));   // no getter: a header condition can never fire (fail open)
            if ($expect['reason'] === 'rule') {
                self::assertNotSame($expect['rule'], $blind->rule);
            } else {
                self::assertSame($expect['reason'], $blind->reason);
            }
        }
        self::assertGreaterThan(0, $seen);
    }

    #[DataProvider('sources')]
    public function testInterleavedMatchersKeepStateApart(string $source): void
    {
        $a = self::matcher($source, 'v4-basic');
        $b = self::matcher($source, 'v4-empty');
        for ($i = 0; $i < 20; $i++) {
            self::assertSame('ip6', $a->match(new MatchInput(ip: '2001:db8::1'))->reason);
            self::assertFalse($b->match(new MatchInput(ip: '2001:db8::1'))->block);
            self::assertFalse($a->match(new MatchInput(ip: '2001:db8::2'))->block);
        }
    }

    public function testTheTwoWordSourcesReadTheSameWords(): void
    {
        $mem = self::words('memory', 'blk5/v5-rules.bin');
        $file = self::words('file', 'blk5/v5-rules.bin');
        self::assertSame($mem->length(), $file->length());
        foreach ([0, 1, 2, 100, 65536, $mem->length() - 1] as $i) {
            self::assertSame($mem->get($i), $file->get($i), "word {$i}");
        }
        self::assertSame($mem->range(2, 30), $file->range(2, 30));
    }
}
