#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Re-vendors @camada/browser's auto build into src/BeaconJs.php.
 *
 * Usage: php scripts/sync-beacon.php [path/to/camada-browser]   (defaults to the sibling checkout)
 * Run `npm run build` in camada-browser first; tests/BeaconJsTest.php fails until the two agree.
 */
$root = dirname(__DIR__);
$browser = $argv[1] ?? dirname($root) . '/camada-browser';
$src = file_get_contents($browser . '/dist/auto.global.js');
$pkg = json_decode((string) file_get_contents($browser . '/package.json'), true);
if (!is_string($src) || !is_array($pkg) || !is_string($pkg['version'] ?? null)) {
    fwrite(STDERR, "no built @camada/browser at {$browser} (npm run build there first)\n");
    exit(1);
}
$version = $pkg['version'];
$out = "<?php\n\n"
    . "declare(strict_types=1);\n\n"
    . "namespace Camada;\n\n"
    . "// GENERATED by scripts/sync-beacon.php — do not edit. The first-party beacon (@camada/browser's\n"
    . "// dist/auto.global.js) vendored as a class constant: served at /_cam/b.js from opcache, with no\n"
    . "// runtime file read. tests/BeaconJsTest.php pins it to the sibling build byte for byte.\n"
    . "final class BeaconJs\n"
    . "{\n"
    . '    public const VERSION = ' . var_export($version, true) . ";\n"
    . '    public const SHA256 = ' . var_export(hash('sha256', $src), true) . ";\n"
    . '    public const JS = ' . var_export($src, true) . ";\n"
    . "}\n";
file_put_contents($root . '/src/BeaconJs.php', $out);
echo "BeaconJs.php: @camada/browser/{$version}, " . strlen($src) . " bytes\n";
